---
version: "3.7"
services:

########################################################################################
# Pihole
# https://github.com/pi-hole/docker-pi-hole/
# https://docs.pi-hole.net/
#
# Note: Once running, navigate to https://pihole.${FQDN}/admin
########################################################################################

  pihole:
    container_name: pihole
    domainname: docker
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      # - '67:67/udp'
      #- 'XXXX:80'
      #- 'YYYY:443'
    restart: unless-stopped
    volumes:
      - ${CONFIG_DIR}/pihole/pihole:/etc/pihole
      - ${CONFIG_DIR}/pihole/pihole.log:/var/log/pihole.log
      - ${CONFIG_DIR}/pihole/dnsmask.d:/etc/dnsmasq.d
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    networks:
      - backend
    environment:
      - ServerIP=192.168.1.15
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=${FQDN}/pihole
      - VIRTUAL_PORT=80
      - TZ=${TZ}
      #- WEBPASSWORD=RandomWhenCommentedOut
      - DNS1=127.0.0.1
      - DNS2=1.1.1.1
      #- DNS2=1.0.0.1
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.pihole-rtr.entrypoints=websecure"
      - "traefik.http.routers.pihole-rtr.rule=HostHeader(`pihole.$FQDN`)"
      - "traefik.http.routers.pihole-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.pihole-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.pihole-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.http.routers.pihole-rtr.middlewares=chain-oauth2-proxy@file" # OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.pihole-rtr.service=pihole-svc"
      - "traefik.http.services.pihole-svc.loadbalancer.server.port=80"

networks:
  backend:
    external:
      name: backend
      #run: docker network create backend