---
version: '3.7'

services:

  vpn:
    container_name: vpn
    hostname: vpn
    build: .
    #image: alpine:latest
    cap_add:
      - NET_ADMIN
    #devices:
      #- /dev/net/tun
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - frontend
      - backend
      - remote
    tty: true
    environment:
      - 'PS1=\\h:\\w\\$$ '

  host1:
    container_name: host1
    hostname: host1
    image: alpine:latest
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - backend
    tty: true
    environment:
      - 'PS1=\\h:\\w\\$$ '
    command:
      - ''

  remote1:
    container_name: remote1
    hostname: remote1
    image: alpine:latest
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    dns:
      - 1.1.1.1
      - 1.0.0.1
    networks:
      - remote
    tty: true
    environment:
      - 'PS1=\\h:\\w\\$$ '

networks:
  frontend:
    name: frontend
    #driver_opts:
      #com.docker.network.bridge.enable_ip_masquerade: 'true'
  backend:
    name: backend
    #internal: true
    #attachable: true
  remote:
    name: remote