---
version: '3.7'
services:

  sing-box:
    image: ghcr.io/sagernet/sing-box:latest
    container_name: sing-box
    ports:
      - 8443:8443
    volumes:
      - ${CONFIG_DIR}/sing-box:/etc/sing-box
      - ${CONFIG_DIR}/traefik2/acme/dump:/certs
    restart: always
    networks:
      - traefik
    command: ["run", "-c", "/etc/sing-box/config.json"]
    #command: ["version"] 
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.sing-box-rtr.entrypoints=websecure"
      - "traefik.http.routers.sing-box-rtr.rule=Host(`my.$FQDN`)"
      - "traefik.http.routers.sing-box-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.sing-box-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.sing-box-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.http.routers.sing-box-rtr.middlewares=chain-oauth2-proxy@file" # OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.sing-box-rtr.service=sing-box-svc"
      - "traefik.http.services.sing-box-svc.loadbalancer.server.port=8443"


  traefik-certs-dumper:
    image: ldez/traefik-certs-dumper:latest
    container_name: cert-dumper
    networks:
      - traefik
    entrypoint: sh -c '
      traefik-certs-dumper file --crt-ext=.pem --key-ext=.pem --domain-subdir --version v2 --watch
      --source /data/acme.json --dest /data/dump'
    volumes:
      - ${CONFIG_DIR}/traefik2/acme:/data


networks:
  traefik:
    name: traefik
    external: true
    #run: docker network create traefik
