---
version: '3.7'
services:

  sing-box:
    image: ghcr.io/sagernet/sing-box:latest
    container_name: sing-box
    volumes:
      - ${CONFIG_DIR}/sing-box:/etc/sing-box
    restart: always
    networks:
      - traefik
    command: ["run", "-c", "/etc/sing-box/config.json"]
    #command: ["version"] 

  traefik-certs-dumper:
    image: ldez/traefik-certs-dumper:latest
    container_name: cert-dumper
    networks:
      - traefik
    entrypoint: sh -c '
      traefik-certs-dumper file --crt-ext=.pem --key-ext=.pem --domain-subdir --version v2 --watch
      --source /data/acme.json --dest /data/dump'
    volumes:
      - ${CONFIG_DIR}/traefik2/acme:/data


networks:
  traefik:
    name: traefik
    external: true
    #run: docker network create traefik
