---
version: '3.7'
services:

########################################################################################
# Home Assistant
# https://www.home-assistant.io/installation/raspberrypi#docker-compose
########################################################################################

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG_DIR}/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 8123:8123
    restart: unless-stopped
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0