---
version: '3.7'
services:

########################################################################################
# Home Assistant
# https://www.home-assistant.io/installation/raspberrypi#docker-compose
########################################################################################

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${CONFIG_DIR}/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - 8123:8123
    restart: unless-stopped
    privileged: true
    network_mode: host
    # devices:
    #   - /dev/ttyUSB0:/dev/ttyUSB0

  zwavejs2mqtt:
    container_name: zwavejs2mqtt
    image: zwavejs/zwavejs2mqtt:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - SESSION_SECRET=${ZWAVEJS2MQTT_SESSION_SECRET}
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      - TZ=${TZ}
    networks:
      - backend
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/serial/by-id/${ZWAVE_DEVICE_ID}:/dev/zwave'
    volumes:
      - ${CONFIG_DIR}/zwavejs2mqtt:/usr/src/app/store
    ports:
      - '3000:3000' # port for Z-Wave JS websocket server
      # - '8091:8091' # port for web interface
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.zwavejs2mqtt-rtr.entrypoints=websecure"
      - "traefik.http.routers.zwavejs2mqtt-rtr.rule=Host(`zwavejs2mqtt.$FQDN`)"
      - "traefik.http.routers.zwavejs2mqtt-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.zwavejs2mqtt-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.zwavejs2mqtt-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      - "traefik.http.routers.zwavejs2mqtt-rtr.middlewares=chain-oauth@file" # OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.zwavejs2mqtt-rtr.service=zwavejs2mqtt-svc"
      - "traefik.http.services.zwavejs2mqtt-svc.loadbalancer.server.port=8091"

networks:
  backend:
    external:
      name: backend
      #run: docker network create backend
