http:
  routers:
    edgeos-rtr:
      rule: "Host(`edgeos.***FQDN***`)" # need to use HostHeader if using Traefik 2.2.2
      entryPoints:
        - websecure # https
      middlewares:
        - chain-oauth2-proxy@file
      service: edgeos-svc
      tls: true
  services:
    edgeos-svc:
      loadBalancer:
        servers:
          - url: "https://192.168.1.1" # some routers may need to specify "http" instead of "https"
