http:
  routers:
    plex-rtr:
      rule: "Host(`plex.***FQDN***`)"
      entryPoints:
        - websecure # https
      middlewares:
        - chain-no-auth
      service: plex-svc
      tls: true
  services:
    plex-svc:
      loadBalancer:
        servers:
          - url: "http://192.168.1.50:32400/web/index.html"
