---
version: '3.7'
services:

########################################################################################
# oauth2
# https://quay.io/repository/pusher/oauth2_proxy
# https://github.com/pusher/oauth2_proxy
# https://github.com/pusher/oauth2_proxy/issues/46
########################################################################################

  oauth2:
    container_name: oauth2
    image: quay.io/pusher/oauth2_proxy:latest-armv6
    command:
      - "-cookie-domain=${FQDN}"
      - "-cookie-secure=true"
      - "-email-domain=*"
      - "-github-org=${GITHUB_ORG}"
      - "-http-address=0.0.0.0:4180"
      - "-pass-access-token"
      - "-provider=github"
      - "-redirect-url=https://${FQDN}/oauth2/callback"
      - "-set-authorization-header"
      - "-set-xauthrequest"
      - "-whitelist-domain=.${FQDN}"
    environment:
      - "OAUTH2_PROXY_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}"
      - "OAUTH2_PROXY_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}"
      - "OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}"
    expose:
      - "4180"
    #ports:
      #- 4180:4180
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.oauth-rtr.entrypoints=websecure"
      #- "traefik.http.routers.oauth-rtr.rule=HostHeader(`oauth.${FQDN}`)"
      - "traefik.http.routers.oauth-rtr.rule=HostHeader(`oauth.${FQDN?err}`) || PathPrefix(`/oauth2`)"
      - "traefik.http.routers.oauth-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.oauth-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.oauth-rtr.service=oauth-svc"
      - "traefik.http.services.oauth-svc.loadbalancer.server.port=4180"
      ## Other labels
      - "traefik.http.middlewares.oauth-verify.forwardAuth.address=http://oauth:4180/oauth2/auth"
      - "traefik.http.middlewares.oauth-verify.forwardAuth.trustForwardHeader=true"
      - "traefik.http.middlewares.oauth-verify.forwardAuth.authResponseHeaders=X-Auth-Request-User,X-Auth-Request-Email,Set-Cookie"
      - "traefik.http.middlewares.oauth-signin.errors.service=oauth@file"
      - "traefik.http.middlewares.oauth-signin.errors.status=401"
      - "traefik.http.middlewares.oauth-signin.errors.query=/oauth2/sign_in"
      - "traefik.http.routers.oauth.entrypoints=websecure"
      - "traefik.http.routers.oauth.tls.certResolver=default"
      - "traefik.http.routers.oauth.service=oauth@file"
      - "traefik.http.services.oauth.loadbalancer.server.port=4180"
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    external:
      name: backend
      #run: docker network create backend