---
version: '3.8'
services:

########################################################################################
# oauth2
# https://quay.io/repository/pusher/oauth2_proxy
# https://github.com/pusher/oauth2_proxy
# https://github.com/pusher/oauth2_proxy/issues/46
########################################################################################

  oauth2:
    container_name: oauth2
    image: quay.io/oauth2-proxy/oauth2-proxy:latest-arm64
    command:
      - "--cookie-domain=${FQDN}"
      - "--cookie-secure=true"
      - "--email-domain=*"
      # - "--github-org=${GITHUB_ORG}"
      - "--github-user=${GITHUB_USER}" # allow logins by username, separated by a comma
      - "--scope=user:email"
      - "--http-address=0.0.0.0:4180"
      - "--reverse-proxy=true"
      - "--provider=github"
      - "--redirect-url=https://oauth2.${FQDN}/oauth2/callback"
      - "--whitelist-domain=.${FQDN}"
      - "--upstream=static://200"
      - "--skip-provider-button=false"
    environment:
      - "OAUTH2_PROXY_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}"
      - "OAUTH2_PROXY_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}"
      - "OAUTH2_PROXY_COOKIE_SECRET=${OAUTH2_PROXY_COOKIE_SECRET}"
    expose:
      - "4180"
    #ports:
      #- 4180:4180
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.oauth2-rtr.entrypoints=websecure"
      # - "traefik.http.routers.oauth2-rtr.rule=Host(`oauth2.${FQDN}`)"
      # - "traefik.http.routers.oauth2-rtr.rule=Host(`oauth2.${FQDN}`) && PathPrefix(`/oauth2`)"
      - "traefik.http.routers.oauth2-rtr.rule=Host(`oauth2.${FQDN}`) || PathPrefix(`/oauth2`)"
      - "traefik.http.routers.oauth2-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.oauth2-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.oauth2-rtr.service=oauth2-svc"
      - "traefik.http.services.oauth2-svc.loadbalancer.server.port=4180"
    networks:
      - traefik
    restart: unless-stopped

  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.whoami-rtr.entrypoints=websecure"
      - "traefik.http.routers.whoami-rtr.rule=Host(`whoami.$FQDN`)"
      - "traefik.http.routers.whoami-rtr.tls=true"
      ## Middlewares
      # - "traefik.http.routers.whoami-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.whoami-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      - "traefik.http.routers.whoami-rtr.middlewares=chain-oauth2@file" # OAuth 2.0
      # - "traefik.http.routers.whoami-rtr.middlewares=oauth2-signin,oauth2-verify,default-https"
      ## HTTP Services
      - "traefik.http.routers.whoami-rtr.service=whoami-svc"
      - "traefik.http.services.whoami-svc.loadbalancer.server.port=80"

networks:

  traefik:
    name: traefik
    external: true
    #run: docker network create traefik
