services:

  autoheal:
    image: willfarrell/autoheal:latest
    container_name: autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal
      - APPRISE_URL=http://apprise:8000/notify/6f383be0229c371400b4f2a84cbdb23ce0481f166d6c49044fcbf811c02ee831
    #network_mode: none
    networks:
      - traefik
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: autoheal

networks:
  traefik:
    name: traefik
    external: true
    #run: docker network create traefik

