services:
  invoiceninja-nginx:
    image: nginx
    container_name: invoiceninja-nginx
    restart: always
    environment: 
      - APP_URL=http://invoiceninja.${FQDN}
    volumes:
      # Vhost configuration
      #- ./config/caddy/Caddyfile:/etc/caddy/Caddyfiledocker-com
      # - ./config/nginx/in-vhost.conf:/etc/nginx/conf.d/in-vhost.conf:ro
      - ${VOLUME_DIR}/invoiceninja/public:/var/www/app/public:ro
    depends_on:
      - invoiceninja-app
    # Run webserver nginx on port 80
    # Feel free to modify depending what port is already occupied
    # ports:
      # - "80:80"
      #- "443:443"
    networks:
      - traefik
    # extra_hosts:
    #   - "in5.localhost:192.168.0.124 " #host and ip
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.in-rtr.entrypoints=websecure"
      - "traefik.http.routers.in-rtr.rule=Host(`in.$FQDN`)"
      - "traefik.http.routers.in-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.in-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.in-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.http.routers.in-rtr.middlewares=chain-oauth2-proxy@file" # OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.in-rtr.service=in-svc"
      - "traefik.http.services.in-svc.loadbalancer.server.port=443"

  invoiceninja-app:
    image: invoiceninja/invoiceninja:5
    container_name: invoiceninja
    environment: 
      - APP_URL=http://invoiceninja.${FQDN}
      - APP_KEY=${IN_APP_KEY}
      - MULTI_DB_ENABLED=false
      - DB_HOST=db
      - DB_DATABASE=ninja
      - DB_USERNAME=ninja
      - DB_PASSWORD=ninja
      - IN_USER_EMAIL=${EMAIL}
      - IN_PASSWORD=${IN_PASSWORD}
    restart: always
    volumes:
      - ${CONFIG_DIR}/invoiceninja/hosts:/etc/hosts:ro
      - ${VOLUME_DIR}/invoiceninja/public:/var/www/app/public:rw,delegated
      - ${VOLUME_DIR}/invoiceninja/storage:/var/www/app/storage:rw,delegated
      - type: bind
        source: ${CONFIG_DIR}/invoiceninja/php/php.ini
        target: /usr/local/etc/php/php.ini
      - type: bind
        source: ${CONFIG_DIR}/invoiceninja/php/php-cli.ini
        target: /usr/local/etc/php/php-cli.ini
    depends_on:
      - invoiceninja-db
    networks:
      - traefik
    # extra_hosts:
    #   - "in5.localhost:192.168.0.124 " #host and ip

  invoiceninja-db:
    image: container-registry.oracle.com/mysql/community-server:8.4-aarch64
    container_name: invoiceninja-db
    # ports:
    #   - "3306:3306"
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=${IN_DB_ROOT_PASSWORD}
      - MYSQL_USER=ninja
      - MYSQL_PASSWORD=${IN_DB_PASSWORD}
      - MYSQL_DATABASE=ninja
    volumes:
      - ${VOLUME_DIR}/invoiceninja:/var/lib/mysql:rw,delegated
    networks:
      - traefik
    # extra_hosts:
    #   - "in5.localhost:192.168.0.124 " #host and ip

networks:
  traefik:
    name: traefik
    external: true
    #run: docker network create traefik