---
version: '3.7'
services:

########################################################################################
# Bitwarden_rs - Bitwarden server API implementation written in Rust compatible with upstream Bitwarden clients
# https://github.com/dani-garcia/bitwarden_rs/wiki/Using-Docker-Compose
########################################################################################

  bitwarden:
    image: bitwardenrs/server:latest
    container_name: bitwarden
    restart: unless-stopped
    volumes:
        - ${CONFIG_DIR}/bitwarden:/data
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN} # https://github.com/dani-garcia/bitwarden_rs/wiki/Enabling-admin-page
      - DOMAIN=https://bitwarden.${FQDN} # Required for correct generation of invite links
      - SIGNUPS_ALLOWED=false
      - SMTP_HOST=${SMTP_SERVER}
      - SMTP_FROM=${EMAIL_FROM}
      - SMTP_PORT=587
      - SMTP_SSL=true # https://github.com/dani-garcia/bitwarden_rs/wiki/SMTP-configuration
      - SMTP_USERNAME=${EMAIL_FROM} # Must 'allow less secure app access' if using Gmail --> https://myaccount.google.com/lesssecureapps?utm_source=google-account&utm_medium=web
      - SMTP_PASSWORD=${EMAIL_PASSWORD}
      - LOG_FILE=/data/bitwarden.log
      - WEBSOCKET_ENABLED=true # Required to use WebSocket notifications
      # - DATABASE_URL=mysql://bitwarden:${BITWARDEN_DBPASS}@maria-bitwarden/bitwarden #FORMAT: DATABASE_URL=mysql://[[user]:[password]@]host[:port][/database]
    networks:
      - backend
    #ports:
      # - 443:443
      # - 80:80
      # - 3012:3012 # For WebSocket
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.bitwarden-rtr.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-rtr.rule=HostHeader(`bitwarden.$FQDN`)"
      - "traefik.http.routers.bitwarden-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.bitwarden-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.bitwarden-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.http.routers.bitwarden-rtr.middlewares=chain-oauth@file" # OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.bitwarden-rtr.service=bitwarden-svc"
      - "traefik.http.services.bitwarden-svc.loadbalancer.server.port=80"
      #---------------------------------
      # WebSocket Traefik configuration
      #---------------------------------
      ## HTTP Routers
      - "traefik.http.routers.bitwarden-websocket-rtr.entrypoints=websecure"
      - "traefik.http.routers.bitwarden-websocket-rtr.rule=HostHeader(`bitwarden.$FQDN`) && Path(`/notifications/hub`)"
      - "traefik.http.routers.bitwarden-websocket-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.bitwarden-websocket-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.bitwarden-websocket-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.http.routers.bitwarden-websocket-rtr.middlewares=chain-oauth@file" # OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.bitwarden-websocket-rtr.service=bitwarden-websocket-svc"
      - "traefik.http.services.bitwarden-websocket-svc.loadbalancer.server.port=3012"

########################################################################################
# MariaDB
# The only official MySQL compatible database compiled for ARM is MariaDB
# https://hub.docker.com/_/mariadb
#
# Notes: https://github.com/dani-garcia/bitwarden_rs/wiki/Using-the-MySQL-Backend
########################################################################################
#
#  mariadb:
#    image: mariadb
#    container_name: mariadb
#    environment:
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    restart: always
#    networks:
#      - backend
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOTPW}
#      MYSQL_USER: ${USERNAME}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_DATABASE: ${DB_NAME}
#    volumes:
#      - ./data/database:/docker-entrypoint-initdb.d
#      - ${VOLUME_DIR}/mariadb:/var/lib/mysql #Data Directory

networks:
  backend:
    external:
      name: backend
      #run: docker network create --name=backend

