###############################################################
#                   Authelia configuration                    #
###############################################################
server:
  host: 0.0.0.0
  port: 9091
log:
  level: debug
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
# jwt_secret: ${AUTHELIA_JWT_SECRET_FILE}
default_redirection_url: https://authelia.***FQDN***
totp:
  issuer: authelia.com
  period: 30
  skew: 1

# Enable the following for Duo Push Notification support
# https://www.authelia.com/docs/features/2fa/push-notifications.html
#duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml
    # customize passwords based on https://docs.authelia.com/configuration/authentication/file.html
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024

# https://docs.authelia.com/configuration/access-control.html
access_control:
  default_policy: deny
  rules:
    # Rules applied to everyone
    - domain: authelia.***FQDN***
      policy: bypass
    - domain: "***FQDN***"
      policy: one_factor
    - domain: "*.***FQDN***"
      policy: one_factor
    # - domain: secure.example.com
    #   policy: two_factor

session:
  name: authelia_session
  # This secret can also be set using the env variables AUTHELIA_SESSION_SECRET_FILE
  # secret: ${AUTHELIA_SESSION_SECRET_FILE}
  expiration: 3600 # 1 hour
  inactivity: 300 # 5 minutes
  domain: ***FQDN*** # Should match whatever your root protected domain is

# Optional. Can improve performance on a busy system. If not enabled, session info is stored in memory.
  # redis:
    # host: redis
    # port: 6379
    # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
    # password: $AUTHELIA_SESSION_REDIS_PASSWORD_FILE}

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  local:
    path: /config/db.sqlite3

notifier:
  # For testing purpose, notifications can be sent in a file
  filesystem:
    filename: /config/notification.txt
  # For email, create an app password, following: https://support.google.com/accounts/answer/185833?hl=en
#   smtp:
#     username: test
#     # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
#     password: ${AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE}
#     host: smtp.gmail.com
#     port: 587
#     sender: admin@example.com
