---
version: '3.7'

secrets:
  authelia_jwt_secret:
    file: ${CONFIG_DIR}/authelia/secrets/authelia_jwt_secret
  authelia_session_secret:
    file: ${CONFIG_DIR}/authelia/secrets/authelia_session_secret

services:
  # Authelia (Lite) - Self-Hosted Single Sign-On and Two-Factor Authentication
  authelia:
    container_name: authelia
    # Check this before upgrading: https://github.com/authelia/authelia/blob/master/BREAKING.md
    # image: authelia/authelia:latest
    image: authelia/authelia:latest
    restart: always
    networks:
      - backend
    # ports:
    #   - "9091:9091"
    volumes:
      - ${CONFIG_DIR}/authelia:/config
    environment:
      - TZ=${TZ}
      - FQDN=${FQDN}
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/authelia_jwt_secret
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/authelia_session_secret
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.authelia-rtr.entrypoints=websecure"
      - "traefik.http.routers.authelia-rtr.rule=Host(`authelia.${FQDN}`)"
      ## Middlewares
      - "traefik.http.routers.authelia-rtr.middlewares=chain-authelia@file"
      ## HTTP Services
      - "traefik.http.routers.authelia-rtr.service=authelia-svc"
      - "traefik.http.services.authelia-svc.loadbalancer.server.port=9091"

networks:
  backend:
    external:
      name: backend
      #run: docker network create backend