---
version: '3.7'
services:

########################################################################################
# Gotify
# https://gotify.net/docs/config
########################################################################################

  gotify:
    image: gotify/server-arm7 # for Raspberry Pi
    container_name: gotify
    restart: unless-stopped
    volumes:
        - ${CONFIG_DIR}/gotify:/app/data
    environment:
        - GOTIFY_SERVER_PORT=80
        #- GOTIFY_SERVER_LISTENADDR=
        - GOTIFY_SERVER_SSL_ENABLED=false
        - GOTIFY_SERVER_SSL_REDIRECTTOHTTPS=true
        #- GOTIFY_SERVER_SSL_LISTENADDR=
        - GOTIFY_SERVER_SSL_PORT=443
        #- GOTIFY_SERVER_SSL_CERTFILE=
        #- GOTIFY_SERVER_SSL_CERTKEY=
        #- GOTIFY_SERVER_SSL_LETSENCRYPT_ENABLED=false
        #- GOTIFY_SERVER_SSL_LETSENCRYPT_ACCEPTTOS=false
        #- GOTIFY_DATABASE_DIALECT=sqlite3
        #- GOTIFY_DATABASE_CONNECTION=gotify.db
        - GOTIFY_DEFAULTUSER_NAME=${USERNAME}
        - GOTIFY_DEFAULTUSER_PASS=${GOTIFY_PASSWORD}
    networks:
      - backend
    #ports:
      #- 443:443
      #- 80:80
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gotify-rtr.entrypoints=websecure"
      - "traefik.http.routers.gotify-rtr.rule=HostHeader(`gotify.$FQDN`)"
      - "traefik.http.routers.gotify-rtr.tls=true"
      ## Middlewares
      - "traefik.http.routers.gotify-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.gotify-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      # - "traefik.http.routers.gotify-rtr.middlewares=chain-oauth@file" # OAuth 2.0
      ## HTTP Services
      - "traefik.http.routers.gotify-rtr.service=gotify-svc"
      - "traefik.http.services.gotify-svc.loadbalancer.server.port=80"


networks:
  backend:
    external:
      name: backend
      #run: docker network create --name=backend