name: babybuddy
services:

services:
  babybuddy:
    image: lscr.io/linuxserver/babybuddy
    container_name: babybuddy
    volumes:
      - ${DATA_DIR}/babybuddy:/config
    # ports:
    #   - 8000:8000
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - autoheal=true
      - traefik.enable=true
      ## HTTP Routers
      - traefik.http.routers.babybuddy-rtr.entrypoints=websecure
      - traefik.http.routers.babybuddy-rtr.rule=Host(`babybuddy.$FQDN2`)
      - traefik.http.routers.babybuddy-rtr.tls=true
      ## Middlewares
      - traefik.http.routers.babybuddy-rtr.middlewares=chain-no-auth@file # No Authentication
      # - traefik.http.routers.babybuddy-rtr.middlewares=chain-basic-auth@file # Basic Authentication
      # - traefik.http.routers.babybuddy-rtr.middlewares=chain-oauth2-proxy@file # OAuth 2.0
      ## HTTP Services
      - traefik.http.routers.babybuddy-rtr.service=babybuddy-svc
      - traefik.http.services.babybuddy-svc.loadbalancer.server.port=8000

networks:
  traefik:
    name: traefik
    external: true
    #run: docker network create traefik